# Generated by Django 4.1 on 2022-10-26 18:19

from django.db import migrations, models
import django.db.models.deletion
from movie.models import Director


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_imdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.director'),
        ),
    ]
