# Generated by Django 4.1 on 2022-10-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actores',
            field=models.ManyToManyField(to='movie.actor'),
        ),
    ]
